# -*- coding: utf-8 -*-
"""board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQK1pLVZ1YibGVf-W87YGNe7ibk7xvE1
"""

board = ["-","-","-",
         "-","-","-",
         "-","-","-",]

def print_board():
  print(board[0] + " | " + board[1] + " | " + board[2])
  print("---------")
  print(board[3] + " | " + board[4] + " | " + board[5])
  print("---------")
  print(board[6] + " | " + board[7] + " | " + board[8])

print_board()